<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Instartups.Infrastructure\Instartups.Infrastructure.csproj" />
  </ItemGroup>


	<Target Name="HuskyInstall" BeforeTargets="Restore" Condition="'$(HUSKY)' != '0' AND !Exists('$(MSBuildThisFileDirectory)..\\.husky\\_\\husky.sh')">
		<Exec Command="dotnet tool restore" WorkingDirectory="$(MSBuildThisFileDirectory).." />
		<Exec Command="dotnet husky install" WorkingDirectory="$(MSBuildThisFileDirectory).." />
	</Target>

</Project>
