// <auto-generated />
using System;
using Instartups.Command.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Instartups.Command.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Instartups.Command.Domain.Entities.CurtidaPostagemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset?>("DataAtualizacao")
                        .HasColumnType("timestamptz")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamptz")
                        .HasColumnName("data_criacao");

                    b.Property<Guid>("PerfilAutorCurtidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("perfil_autor_curtida_id");

                    b.Property<Guid>("PostagemId")
                        .HasColumnType("uuid")
                        .HasColumnName("postagem_id");

                    b.HasKey("Id");

                    b.HasIndex("DataAtualizacao");

                    b.HasIndex("DataCriacao");

                    b.HasIndex("PerfilAutorCurtidaId");

                    b.HasIndex("PostagemId");

                    b.ToTable("curtidas_postagens", (string)null);
                });

            modelBuilder.Entity("Instartups.Command.Domain.Entities.InvestidorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset?>("DataAtualizacao")
                        .HasColumnType("timestamptz")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamptz")
                        .HasColumnName("data_criacao");

                    b.Property<Guid>("PerfilId")
                        .HasColumnType("uuid")
                        .HasColumnName("perfil_id");

                    b.Property<string>("TeseInvestimento")
                        .IsRequired()
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("tese_investimento");

                    b.Property<decimal>("TicketMaximo")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("ticket_maximo");

                    b.Property<decimal>("TicketMinimo")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("ticket_minimo");

                    b.HasKey("Id");

                    b.HasIndex("DataAtualizacao");

                    b.HasIndex("DataCriacao");

                    b.HasIndex("PerfilId")
                        .IsUnique();

                    b.ToTable("investidores", (string)null);
                });

            modelBuilder.Entity("Instartups.Command.Domain.Entities.MidiaPostagemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset?>("DataAtualizacao")
                        .HasColumnType("timestamptz")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamptz")
                        .HasColumnName("data_criacao");

                    b.Property<Guid?>("PostagemEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PostagemId")
                        .HasColumnType("uuid")
                        .HasColumnName("postagem_id");

                    b.Property<int>("TipoMidia")
                        .HasColumnType("int")
                        .HasColumnName("tipo_midia");

                    b.Property<string>("UrlMidia")
                        .IsRequired()
                        .HasColumnType("varchar(400)")
                        .HasColumnName("url_midia");

                    b.HasKey("Id");

                    b.HasIndex("DataAtualizacao");

                    b.HasIndex("DataCriacao");

                    b.HasIndex("PostagemEntityId");

                    b.HasIndex("PostagemId");

                    b.ToTable("midias_postagens", (string)null);
                });

            modelBuilder.Entity("Instartups.Command.Domain.Entities.PerfilEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<Point>("Coordenada")
                        .IsRequired()
                        .HasColumnType("geography(Point, 4326)")
                        .HasColumnName("coordenada");

                    b.Property<DateTimeOffset?>("DataAtualizacao")
                        .HasColumnType("timestamptz")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamptz")
                        .HasColumnName("data_criacao");

                    b.Property<string>("ImagemFundoUrl")
                        .HasColumnType("varchar(400)")
                        .HasColumnName("imagem_fundo_url");

                    b.Property<string>("ImagemPerfilUrl")
                        .HasColumnType("varchar(400)")
                        .HasColumnName("imagem_perfil_url");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<short>("TipoPerfil")
                        .HasColumnType("smallint")
                        .HasColumnName("tipo_perfil");

                    b.Property<int>("TotalCurtidas")
                        .HasColumnType("integer")
                        .HasColumnName("total_curtidas");

                    b.Property<int>("TotalSeguidores")
                        .HasColumnType("integer")
                        .HasColumnName("total_seguidores");

                    b.Property<int>("TotalSeguindo")
                        .HasColumnType("integer")
                        .HasColumnName("total_seguindo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("DataAtualizacao");

                    b.HasIndex("DataCriacao");

                    b.ToTable("perfis", (string)null);
                });

            modelBuilder.Entity("Instartups.Command.Domain.Entities.PerfilSeguidorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset?>("DataAtualizacao")
                        .HasColumnType("timestamptz")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamptz")
                        .HasColumnName("data_criacao");

                    b.Property<Guid>("SeguidoId")
                        .HasColumnType("uuid")
                        .HasColumnName("seguido_id");

                    b.Property<Guid>("SeguidorId")
                        .HasColumnType("uuid")
                        .HasColumnName("seguidor_id");

                    b.HasKey("Id");

                    b.HasIndex("DataAtualizacao");

                    b.HasIndex("DataCriacao");

                    b.HasIndex("SeguidoId");

                    b.HasIndex("SeguidorId", "SeguidoId")
                        .IsUnique();

                    b.ToTable("perfil_seguidores", (string)null);
                });

            modelBuilder.Entity("Instartups.Command.Domain.Entities.PostagemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("autor_id");

                    b.Property<DateTimeOffset?>("DataAtualizacao")
                        .HasColumnType("timestamptz")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamptz")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("descricao");

                    b.Property<long>("TotalCurtidas")
                        .HasColumnType("bigint")
                        .HasColumnName("total_curtidas");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("DataAtualizacao");

                    b.HasIndex("DataCriacao");

                    b.ToTable("postagens", (string)null);
                });

            modelBuilder.Entity("Instartups.Command.Domain.Entities.StartupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset?>("DataAtualizacao")
                        .HasColumnType("timestamptz")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamptz")
                        .HasColumnName("data_criacao");

                    b.Property<DateOnly>("DataFundacao")
                        .HasColumnType("date")
                        .HasColumnName("data_fundacao");

                    b.Property<Guid>("PerfilId")
                        .HasColumnType("uuid")
                        .HasColumnName("perfil_id");

                    b.Property<string>("Pitch")
                        .IsRequired()
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("pitch");

                    b.Property<short>("TamanhoEquipe")
                        .HasColumnType("smallint")
                        .HasColumnName("tamanho_equipe");

                    b.Property<decimal>("ValorBuscado")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_buscado");

                    b.HasKey("Id");

                    b.HasIndex("DataAtualizacao");

                    b.HasIndex("DataCriacao");

                    b.HasIndex("PerfilId")
                        .IsUnique();

                    b.ToTable("startups", (string)null);
                });

            modelBuilder.Entity("Instartups.Command.Domain.Entities.CurtidaPostagemEntity", b =>
                {
                    b.HasOne("Instartups.Command.Domain.Entities.PerfilEntity", "PerfilAutorCurtida")
                        .WithMany()
                        .HasForeignKey("PerfilAutorCurtidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Instartups.Command.Domain.Entities.PostagemEntity", "Postagem")
                        .WithMany()
                        .HasForeignKey("PostagemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PerfilAutorCurtida");

                    b.Navigation("Postagem");
                });

            modelBuilder.Entity("Instartups.Command.Domain.Entities.InvestidorEntity", b =>
                {
                    b.HasOne("Instartups.Command.Domain.Entities.PerfilEntity", "Perfil")
                        .WithOne("Investidor")
                        .HasForeignKey("Instartups.Command.Domain.Entities.InvestidorEntity", "PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Instartups.Command.Domain.Entities.MidiaPostagemEntity", b =>
                {
                    b.HasOne("Instartups.Command.Domain.Entities.PostagemEntity", null)
                        .WithMany("MidiasPostagem")
                        .HasForeignKey("PostagemEntityId");

                    b.HasOne("Instartups.Command.Domain.Entities.PostagemEntity", "Postagem")
                        .WithMany()
                        .HasForeignKey("PostagemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Postagem");
                });

            modelBuilder.Entity("Instartups.Command.Domain.Entities.PerfilSeguidorEntity", b =>
                {
                    b.HasOne("Instartups.Command.Domain.Entities.PerfilEntity", "Seguido")
                        .WithMany()
                        .HasForeignKey("SeguidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Instartups.Command.Domain.Entities.PerfilEntity", "Seguidor")
                        .WithMany()
                        .HasForeignKey("SeguidorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Seguido");

                    b.Navigation("Seguidor");
                });

            modelBuilder.Entity("Instartups.Command.Domain.Entities.PostagemEntity", b =>
                {
                    b.HasOne("Instartups.Command.Domain.Entities.PerfilEntity", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("Instartups.Command.Domain.Entities.StartupEntity", b =>
                {
                    b.HasOne("Instartups.Command.Domain.Entities.PerfilEntity", "Perfil")
                        .WithOne("Startup")
                        .HasForeignKey("Instartups.Command.Domain.Entities.StartupEntity", "PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Instartups.Command.Domain.Entities.PerfilEntity", b =>
                {
                    b.Navigation("Investidor");

                    b.Navigation("Startup");
                });

            modelBuilder.Entity("Instartups.Command.Domain.Entities.PostagemEntity", b =>
                {
                    b.Navigation("MidiasPostagem");
                });
#pragma warning restore 612, 618
        }
    }
}
