<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Instartups.Command.Domain\Instartups.Command.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Mapster.DependencyInjection" Version="10.0.13" />
  </ItemGroup>
</Project>
